#! /usr/bin/env python3
#! python3
# a program to pick a random word and letting the player guess the word, uses a dictionary to replace 0'es in the word to print

import random
from nltk.corpus import words
word_list = words.words()

# picking a random word and assigning it a dict
chars = {}
level = str(input('1= easy, 2=medium, 3=hard: '))
easy = []
medium = []
hard = []


# Give the user 6 guesses
def playGame():
    if level == '1':
        for word in word_list:
            if len(word) < 5:
                easy.append(word)
        gWord = random.choice(easy)
        l = 12
    elif level == '2':
        for word in word_list:
            if len(word) < 7:
                medium.append(word)
        gWord = random.choice(medium)
        l = 8
    elif level == '3':
        for word in word_list:
            if 7 < len(word):
                hard.append(word)
        gWord = random.choice(hard)
        l = 10
    for d in range(l):
        for i in gWord:
            chars.setdefault(i, 0)
            print(chars[i], end=' ')
        guesses = str(d)
        print('\nGuesses: '+guesses)
        print('Guess a letter or the word!: ')
        guess = input()
        if guess == gWord:
            print('Good job! You did it in '+guesses+' guess(es)!')
            break
        if guess in gWord:
            print(guess+' is in the hidden word!')
            chars[guess] = guess
            l+1
        else:
            print('guess not in the word! You have '+str(l-(d+1))+' guesses left')

    print('The word was '+gWord)

playGame()
